# Generated by Django 2.2 on 2023-05-23 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryAdress',
            new_name='DeliveryAddress',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoty',
            new_name='category',
        ),
    ]
